name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Build & Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install Dependencies
        working-directory: client
        run: npm ci

      - name: Fetch lan-play binaries
        shell: bash
        run: |
          mkdir -p client/bin
          curl -L -o client/bin/lan-play-darwin-arm64 https://github.com/spacemeowx2/switch-lan-play/releases/download/v0.2.3/lan-play-macos-arm64
          curl -L -o client/bin/lan-play-darwin-amd64 https://github.com/spacemeowx2/switch-lan-play/releases/download/v0.2.3/lan-play-macos
          curl -L -o client/bin/lan-play-win32-amd64.exe https://github.com/spacemeowx2/switch-lan-play/releases/download/v0.2.3/lan-play-win64.exe
          curl -L -o client/bin/lan-play-linux-amd64 https://github.com/spacemeowx2/switch-lan-play/releases/download/v0.2.3/lan-play-linux
          chmod +x client/bin/lan-play-*

      - name: Set App Version from Git Tag
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "Setting version to $VERSION"
            cd client
            npm --no-git-tag-version version $VERSION --allow-same-version
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "Setting version to $VERSION"
            cd client
            npm --no-git-tag-version version $VERSION --allow-same-version
          fi

      - name: Build & Publish Release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd client
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            bash ./build-app.sh mac
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            bash ./build-app.sh win
          else
            bash ./build-app.sh linux
          fi
